import { ApplianceService, ApplianceProduct, WhyChooseItem } from "./types";

export const COMPANY_DETAILS = {
  name: "VELS HOME APPLIANCES",
  tagline: "Smart Appliances. Premium Service. Complete Home Comfort.",
  subtext: "Your trusted destination for home appliances, professional installation, maintenance, and reliable service.",
  phone: "+91 90874 96742",
  phoneFormatted: "+91 90874 96742",
  whatsappNumber: "919087496742",
  email: "support@velshomeappliances.com",
  fixedCharge: 500,
  experienceYears: 15,
  completedServices: "25,000+",
  activeEngineers: "50+",
  satisfactionRate: "99.4%",
  address: "Sri Senthil Rice Mill Compound, Near old Fire Service Office, Mangalam Road, Avinashi - 641654",
  serviceHours: "8:00 AM – 9:30 PM (7 Days a Week • 24/7 Emergency Line)",
};

export const APPLIANCE_SERVICES: ApplianceService[] = [
  {
    id: "ac-service",
    name: "AC Service & Installation",
    category: "Cooling Systems",
    shortDesc: "Comprehensive split, inverter & cassette AC jet servicing, gas charging & error diagnostics.",
    fullDesc: "High-pressure indoor & outdoor jet pump wash, R32/R410A eco-friendly refrigerant gas top-up, PCB board repair, fan motor alignment, and precision copper pipe flare installation.",
    image: "/src/assets/images/ac_service_technician_1787600340398.jpg",
    badge: "Most Booked",
    fixedPrice: 500,
    timeEstimate: "45–60 Mins",
    warranty: "6-Month Guarantee & Warranty",
    commonIssues: ["No Cooling / Warm Air", "Water Leakage from Indoor Unit", "Unusual Noise / Vibrations", "Error Code (E1, E4, CH05)", "Gas Leakage Check"],
    features: ["Foam Jet Deep Cleaning", "Sub-zero Temperature Testing", "Digital Amperage Diagnostics", "Genuine Capacitor & PCB Replacement"],
    iconName: "Wind",
  },
  {
    id: "refrigerator-service",
    name: "Refrigerator Service",
    category: "Refrigeration",
    shortDesc: "Expert repair for frost-free, double-door, side-by-side & smart inverter refrigerators.",
    fullDesc: "Specialized diagnostics for inverter linear compressors, defrost sensors, thermostat calibration, cooling coil ice buildup, internal LED & door gasket sealing.",
    image: "/src/assets/images/refrigerator_service_1787600356195.jpg",
    badge: "Same Day Visit",
    fixedPrice: 500,
    timeEstimate: "40–60 Mins",
    warranty: "6-Month Guarantee & Warranty",
    commonIssues: ["Freezer Cold but Fridge Warm", "Excess Ice Buildup (Defrost Failure)", "Compressor Clicking / Not Starting", "Water Pooling Under Crisper", "Gas Pressure Low"],
    features: ["OG Relay & OLP Parts", "Defrost Heater & Sensor Swap", "Nitrogen Flushing & Re-gassing", "Digital Temperature Profiling"],
    iconName: "Refrigerator",
  },
  {
    id: "washing-machine-service",
    name: "Washing Machine Service",
    category: "Fabric Care",
    shortDesc: "Front load, top load & washer-dryer repair with OG spare parts and error code resolution.",
    fullDesc: "Complete mechanical & electronic overhaul: drain pump descaling, drive motor belt calibration, spider arm & drum bearing overhaul, inlet valve replacement, and suspension shock repair.",
    image: "/src/assets/images/washing_service_1787600376147.jpg",
    badge: "Master Technicians",
    fixedPrice: 500,
    timeEstimate: "45–70 Mins",
    warranty: "6-Month Guarantee & Warranty",
    commonIssues: ["Drain Failure (OE, 5E, E20)", "Excessive Drum Shake / Walking", "Water Not Filling (IE, 4E)", "Door Lock Jammed (dE, dL)", "Motor Not Spinning"],
    features: ["Chemical Descaling Wash", "Digital Vibration Balancing", "Original Shock Absorber Replacement", "Motherboard Micro-soldering"],
    iconName: "Disc",
  },
  {
    id: "tv-service",
    name: "Smart TV Service",
    category: "Home Entertainment",
    shortDesc: "Precision board-level repair for 4K OLED, QLED, LED panels, motherboards & sound systems.",
    fullDesc: "Advanced optical & semiconductor repair: LED backlight strip renewal, T-Con timing controller board repairs, HDMI port replacements, SMPS power supply fix, and firmware flashing.",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80",
    badge: "Clean Room Lab",
    fixedPrice: 500,
    timeEstimate: "60 Mins",
    warranty: "6-Month Guarantee & Warranty",
    commonIssues: ["Sound OK but Screen Black", "Horizontal / Vertical Lines", "TV Won't Turn On (Red Light Blinking)", "WiFi / Smart OS Boot Loop", "Distorted / Crackling Audio"],
    features: ["Direct-lit LED Strip Swap", "T-Con & COF Bonding Diagnostic", "Power Supply Overvoltage Protection", "Firmware Reflash & HDMI Fix"],
    iconName: "Tv",
  },
  {
    id: "microwave-service",
    name: "Microwave & Oven Service",
    category: "Kitchen Tech",
    shortDesc: "High-voltage diagnostics for convection, grill, solo microwaves & built-in ovens.",
    fullDesc: "Certified safety handling for high-voltage magnetrons, HV capacitors, high-voltage diodes, turntable synchronization motors, touchpad membranes, and precision temperature thermostats.",
    image: "https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&w=800&q=80",
    fixedPrice: 500,
    timeEstimate: "30–45 Mins",
    warranty: "6-Month Guarantee & Warranty",
    commonIssues: ["Microwave Runs but Doesn't Heat", "Sparking / Arcing Inside Cavity", "Turntable Plate Not Rotating", "Touch Keypad Buttons Unresponsive", "Trips MCB Switch on Start"],
    features: ["Magnetron Emission Testing", "Mica Sheet Replacement", "Door Interlock Micro-switch Fix", "Thermal Safety Cutoff Calibration"],
    iconName: "Flame",
  },
  {
    id: "geyser-service",
    name: "Geyser / Water Heater Service",
    category: "Water Solutions",
    shortDesc: "Instant & storage water geyser descaling, heating element replacement & thermostat check.",
    fullDesc: "Tank descaling to eliminate hard water limescale, replacement of heavy-duty copper heating elements, dual thermostat safety checks, PRV pressure relief valve replacement, and anti-leak sealing.",
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=800&q=80",
    fixedPrice: 500,
    timeEstimate: "35–50 Mins",
    warranty: "6-Month Guarantee & Warranty",
    commonIssues: ["Water Not Heating Enough", "Electric Current Shock Sensation", "Water Dripping from Tank Base", "Overheating / Steam from Tap", "Power Indicator Not Glowing"],
    features: ["Heavy Copper Element Swap", "Anode Magnesium Rod Renewal", "High-Bar Pressure Relief Valve Check", "Hard Water Limescale Flusher"],
    iconName: "Zap",
  },
  {
    id: "dishwasher-service",
    name: "Dishwasher Service",
    category: "Kitchen Care",
    shortDesc: "Complete maintenance for freestanding & built-in multi-rack dishwashers.",
    fullDesc: "Rotary spray arm unclogging, drain pump impeller clearance, solenoid water inlet valve replacement, turbidity sensor cleaning, and heating element diagnostics for spot-free sparkling dishes.",
    image: "https://images.unsplash.com/photo-1581622558663-b2e33377dfb2?auto=format&fit=crop&w=800&q=80",
    fixedPrice: 500,
    timeEstimate: "45–60 Mins",
    warranty: "6-Month Guarantee & Warranty",
    commonIssues: ["Dishes Still Dirty / Grease Stains", "Water Standing in Bottom Basin", "E24 / Drain Error Alert", "Detergent Tablet Not Dispensing", "Leaking from Door Perimeter"],
    features: ["Spray Jet Pressure Balancing", "Door Seal Gasket Renewal", "Flow Meter Diagnostics", "Anti-flood Sensor Recalibration"],
    iconName: "Sparkles",
  },
  {
    id: "chimney-service",
    name: "Chimney Service & Deep Clean",
    category: "Kitchen Air Care",
    shortDesc: "Deep chemical degreasing, baffle filter cleaning & motor suction optimization.",
    fullDesc: "Disassembly and hot chemical bath for heavy oil carbon sludge, blower fan balance, touch & gesture sensor repair, carbon charcoal filter replacement, and aluminum exhaust pipe sealing.",
    image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
    fixedPrice: 500,
    timeEstimate: "60 Mins",
    warranty: "6-Month Guarantee & Warranty",
    commonIssues: ["Low / Weak Smoke Suction", "Oil Dripping from Chimney Housing", "Loud Grinding Noise from Motor", "Auto-Clean Function Not Working", "Touch Control Unresponsive"],
    features: ["Caustic-Free Chemical Degrease", "Copper Motor Bearing Greasing", "Duct Airflow Velocity Check", "LED Downlight Replacement"],
    iconName: "ShieldAlert",
  },
  {
    id: "mixer-service",
    name: "Mixer & Grinder Service",
    category: "Small Appliances",
    shortDesc: "Overload reset, copper motor rewinding, blade sharpening & coupler replacement.",
    fullDesc: "Repair of heavy-duty 750W/1000W commercial and residential mixer grinders, juicers, and food processors. Genuine jar socket bush, carbon brushes, and rotary speed switch replacements.",
    image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=800&q=80",
    fixedPrice: 500,
    timeEstimate: "30 Mins",
    warranty: "6-Month Guarantee & Warranty",
    commonIssues: ["Mixer Trips Overload Switch", "Burning Smell / Smoke from Base", "Jar Coupler Teeth Broken / Slipping", "Jar Base Leaking Wet Spices", "Speed Control Knob Loose"],
    features: ["High RPM Armature Balancing", "Food-Grade Jar Bush Fitting", "Overload Switch Calibration", "Diamond-Tipped Blade Sharpness"],
    iconName: "Wrench",
  },
  {
    id: "air-purifier-service",
    name: "Air Purifier Service",
    category: "Air Quality",
    shortDesc: "True HEPA H13 filter replacement, laser PM2.5 sensor calibration & motor cleaning.",
    fullDesc: "Full allergen and VOC decontamination: HEPA H13 & Activated Carbon honeycomb filter replacement, UV-C germicidal lamp replacement, optical dust sensor tuning, and silent fan alignment.",
    image: "https://images.unsplash.com/photo-1584483766114-2cea6facdf57?auto=format&fit=crop&w=800&q=80",
    fixedPrice: 500,
    timeEstimate: "30 Mins",
    warranty: "6-Month Guarantee & Warranty",
    commonIssues: ["Filter Replacement Light Flashing", "Unpleasant Odor from Exhaust", "Air Quality Indicator Stays Red", "Fan Whining / Low Air Output", "App Connectivity Offline"],
    features: ["H13 Medical-Grade HEPA Swap", "PM2.5 Laser Sensor Calibration", "Ionizer Output Measurement", "Quiet Aerodynamic Alignment"],
    iconName: "Layers",
  },
];

export const FEATURED_PRODUCTS: ApplianceProduct[] = [
  {
    id: "prod-samsung-ac",
    title: "Samsung WindFree™ AI Inverter 1.5 Ton 5-Star Split AC",
    category: "ac",
    brand: "Samsung",
    image: "/src/assets/images/ac_service_technician_1787600340398.jpg",
    energyRating: "5-Star BEE",
    price: "₹42,990",
    mrp: "₹59,990",
    discount: "28% OFF",
    specs: ["23,000 Micro-holes WindFree Cooling", "Digital Inverter Boost with 73% Energy Save", "Tri-Care PM1.0 Air Purification Filter", "SmartThings AI Auto Cooling"],
    inStock: true,
    warranty: "10-Yr Compressor • 5-Yr PCB Warranty",
  },
  {
    id: "prod-lg-fridge",
    title: "LG 674L Side-by-Side Inverter French Door Refrigerator",
    category: "refrigerator",
    brand: "LG",
    image: "/src/assets/images/refrigerator_service_1787600356195.jpg",
    energyRating: "5-Star BEE",
    price: "₹82,490",
    mrp: "₹1,09,990",
    discount: "25% OFF",
    specs: ["Inverter Linear Compressor", "DoorCooling+ & Hygiene Fresh+™", "Smart Diagnosis & ThinQ Wi-Fi", "UVnano Water Dispenser Nozzle"],
    inStock: true,
    warranty: "10-Yr Compressor • 2-Yr Comprehensive",
  },
  {
    id: "prod-bosch-wash",
    title: "Bosch Serie 8 9.0 Kg AI ActiveOxygen Front Load Washer",
    category: "washing",
    brand: "Bosch",
    image: "/src/assets/images/washing_service_1787600376147.jpg",
    energyRating: "5-Star BEE",
    price: "₹49,990",
    mrp: "₹67,990",
    discount: "26% OFF",
    specs: ["EcoSilence Drive™ Friction-Free Motor", "ActiveOxygen 99.99% Cold Disinfection", "SpeedPerfect 65% Less Wash Time", "Anti-Vibration Side Wall Acoustics"],
    inStock: true,
    warranty: "10-Yr Motor • 3-Yr Comprehensive",
  },
  {
    id: "prod-ifb-wash",
    title: "IFB Senator Plus SXS 8.5 Kg Steam Inverter Front Load",
    category: "washing",
    brand: "IFB",
    image: "/src/assets/images/washing_service_1787600376147.jpg",
    energyRating: "5-Star BEE",
    price: "₹38,990",
    mrp: "₹51,990",
    discount: "25% OFF",
    specs: ["Power Steam® 99.99% Allergen Removal", "Aqua Energie In-Built Hard Water Softener", "Crescent Moon Stainless Steel Drum", "4-Year Super Comprehensive Warranty"],
    inStock: true,
    warranty: "10-Yr Motor • 4-Yr Super Warranty",
  },
  {
    id: "prod-voltas-ac",
    title: "Voltas Maha Adjustable Inverter 1.5 Ton 5-Star Split AC",
    category: "ac",
    brand: "Voltas",
    image: "/src/assets/images/ac_service_technician_1787600340398.jpg",
    energyRating: "5-Star BEE",
    price: "₹37,990",
    mrp: "₹52,990",
    discount: "28% OFF",
    specs: ["Multi-Stage Adjustable Cooling Tonnage", "High Ambient Cooling up to 52°C", "Superdry Monsoon Dehumidification", "100% Grooved Copper Condenser"],
    inStock: true,
    warranty: "10-Yr Compressor • 5-Yr PCB",
  },
  {
    id: "prod-ogeneral-ac",
    title: "O General Tropical Hyper Inverter 2.0 Ton Extreme AC",
    category: "ac",
    brand: "O General",
    image: "/src/assets/images/ac_service_technician_1787600340398.jpg",
    energyRating: "5-Star Heavy Duty",
    price: "₹64,990",
    mrp: "₹84,990",
    discount: "24% OFF",
    specs: ["Heavy-Duty Tropical Rotary Compressor", "Sub-Zero Cooling at 55°C Peak Heat", "Blue Fin Hydrophilic Coated Coils", "Extreme Airflow CFM Throw Distance"],
    inStock: true,
    warranty: "10-Yr Compressor • 5-Yr PCB",
  },
  {
    id: "prod-panasonic-tv",
    title: "Panasonic 65\" Master 4K OLED Cinema Display Google TV",
    category: "tv",
    brand: "Panasonic",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=80",
    energyRating: "A+ Energy Certified",
    price: "₹1,24,990",
    mrp: "₹1,79,990",
    discount: "30% OFF",
    specs: ["Master OLED Panel with HCX Pro AI Processor", "Dolby Vision IQ & Dolby Atmos 60W Sound", "Hollywood Colorist Tuned Dynamic HDR", "Hexa Chroma Drive Pro Color Palette"],
    inStock: true,
    warranty: "3-Yr Panel • 2-Yr Complete",
  },
  {
    id: "prod-whirlpool-fridge",
    title: "Whirlpool Intellifresh Pro 340L 5-Star Convertible Refrigerator",
    category: "refrigerator",
    brand: "Whirlpool",
    image: "/src/assets/images/refrigerator_service_1787600356195.jpg",
    energyRating: "5-Star BEE",
    price: "₹36,490",
    mrp: "₹48,990",
    discount: "26% OFF",
    specs: ["IntelliSense Inverter 10-in-1 Modes", "Adaptive Intelligence 15-Day Garden Freshness", "Microblock Technology 99% Bacterial Defense", "FreshFlow Air Tower with Active Carbon"],
    inStock: true,
    warranty: "10-Yr Compressor • 1-Yr Complete",
  },
  {
    id: "prod-dyson-purifier",
    title: "Dyson Purifier Hot+Cool™ Gen1 Air Purifier & Heater",
    category: "kitchen",
    brand: "Dyson",
    image: "https://images.unsplash.com/photo-1584483766114-2cea6facdf57?auto=format&fit=crop&w=800&q=80",
    energyRating: "Certified Asthma & Allergy Friendly",
    price: "₹46,900",
    mrp: "₹56,900",
    discount: "18% OFF",
    specs: ["Fully Sealed HEPA H13 Standard Purifier", "Captures 99.95% Ultrafine PM0.1 Particles", "Air Multiplier™ Technology 290L/sec", "Remote & Magnetic Docking Control"],
    inStock: true,
    warranty: "2-Yr Comprehensive Brand Warranty",
  },
  {
    id: "prod-prestige-chimney",
    title: "Prestige Oscar 90cm Motion Sensor Filterless Kitchen Chimney",
    category: "kitchen",
    brand: "Prestige",
    image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80",
    energyRating: "High Efficiency",
    price: "₹16,490",
    mrp: "₹26,990",
    discount: "39% OFF",
    specs: ["1400 m³/hr Brushless DC Suction", "Gesture Motion Sensor Hands-Free", "Heat Auto-Clean with Oil Collector Tray", "Toughened Curved Glass Design"],
    inStock: true,
    warranty: "10-Yr Motor • 2-Yr Comprehensive",
  },
  {
    id: "prod-kent-ro",
    title: "Kent Grand Plus Alkaline RO + UV + UF + TDS Water Purifier",
    category: "kitchen",
    brand: "Kent",
    image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=800&q=80",
    energyRating: "Zero Water Wastage",
    price: "₹18,990",
    mrp: "₹23,000",
    discount: "17% OFF",
    specs: ["Multi-Purification RO+UV+UF+Alkaline", "In-tank UV Disinfection for Pure Storage", "Zero Water Wastage Recirculation Pump", "Digital Display of Filter Life & TDS Level"],
    inStock: true,
    warranty: "1-Yr Warranty + 3-Yr Free Service AMC",
  },
  {
    id: "prod-philips-airfryer",
    title: "Philips XXL Connected Digital Airfryer & Convection System",
    category: "kitchen",
    brand: "Philips",
    image: "https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&w=800&q=80",
    energyRating: "Rapid Air Tech",
    price: "₹14,990",
    mrp: "₹21,995",
    discount: "32% OFF",
    specs: ["Twin TurboStar Fat Removal Technology", "7.2L Large Capacity (1.4kg Fries)", "NutriU App Connected Smart Cooking", "Dishwasher-Safe QuickClean Basket"],
    inStock: true,
    warranty: "2-Yr Global Brand Warranty",
  },
];

export const WHY_CHOOSE_ITEMS: WhyChooseItem[] = [
  {
    id: "why-1",
    icon: "UserCheck",
    title: "Experienced Technicians",
    desc: "Every engineer is background-verified, factory-trained, and holds a minimum of 7+ years in high-precision appliance diagnostics.",
    stat: "50+ Master Engineers",
    highlight: "Factory Certified",
  },
  {
    id: "why-2",
    icon: "BadgeIndianRupee",
    title: "Transparent Pricing",
    desc: "Fixed ₹500 visiting and basic service. Upfront quote given before any replacement. Zero hidden rates, zero surprise bills.",
    stat: "₹500 Fixed Base Fee",
    highlight: "No Hidden Costs",
  },
  {
    id: "why-3",
    icon: "Zap",
    title: "Fast 60-90 Min Response",
    desc: "Express rapid doorstep arrival across city zones. We know a broken fridge or leaking AC can't wait.",
    stat: "98.4% On-Time Arrival",
    highlight: "Doorstep Express",
  },
  {
    id: "why-4",
    icon: "Sparkles",
    title: "Quality Service",
    desc: "Comprehensive 24-point electronic testing checklist using modern digital vacuum pumps, clamp meters, and thermal sensors.",
    stat: "6-Month Guarantee & Warranty",
    highlight: "Precision Testing",
  },
  {
    id: "why-5",
    icon: "ShieldCheck",
    title: "100% Genuine OG Parts",
    desc: "We only use original brand-approved spare parts with manufacturer barcodes and official warranty documentation.",
    stat: "Direct OG Sourcing",
    highlight: "Authentic Parts",
  },
  {
    id: "why-6",
    icon: "HeartHandshake",
    title: "Customer Satisfaction",
    desc: "Over 25,000 satisfied home and corporate clients trust VELS as their single-point appliance caretaker.",
    stat: "4.9/5 Star Rating",
    highlight: "25k+ Happy Homes",
  },
];

export const BRAND_PARTNERS = [
  { name: "Samsung", badge: "Smart Care", category: "Cooling & Smart Home" },
  { name: "LG", badge: "Direct Partner", category: "Inverter & Laundry" },
  { name: "Whirlpool", badge: "IntelliFresh Pro", category: "Refrigeration & Wash" },
  { name: "Haier", badge: "Smart Inverter", category: "Bottom Mounted & AC" },
  { name: "Godrej", badge: "Eco-Tech Specialist", category: "Green Inverter" },
  { name: "Panasonic", badge: "Nanoe Tech Care", category: "Japanese Quality" },
  { name: "IFB", badge: "Laundry Master", category: "Front Load & Dishwasher" },
  { name: "Bosch", badge: "German Precision", category: "ActiveOxygen Care" },
  { name: "Voltas", badge: "Cooling Specialist", category: "Maha Inverter AC" },
  { name: "Blue Star", badge: "Precision Cooling", category: "Commercial & Home AC" },
  { name: "Lloyd", badge: "Smart Climate", category: "Havells Brand AC" },
  { name: "O General", badge: "Heavy Duty Tropical", category: "Sub-Zero Extreme AC" },
  { name: "Hitachi", badge: "Expandable Inverter", category: "Tropical AC & Fridge" },
  { name: "Philips", badge: "Air & Culinary", category: "Airfryers & Grooming" },
  { name: "Prestige", badge: "Kitchen Signature", category: "Chimneys & Cookware" },
  { name: "Bajaj", badge: "Home Appliances", category: "Geysers & Mixers" },
  { name: "Havells", badge: "Electrical Master", category: "Fans, Heaters & AC" },
  { name: "Usha", badge: "Air Dynamics", category: "Fans, Irons & Sewing" },
  { name: "Crompton", badge: "Water & Air Tech", category: "Pumps, Geysers & Fans" },
  { name: "Orient", badge: "Aero Series", category: "BLDC Fans & Kitchen" },
  { name: "V-Guard", badge: "Voltage & Water Care", category: "Inverters & Geysers" },
  { name: "Morphy Richards", badge: "British Heritage", category: "OTG, Coffee & Toasters" },
  { name: "Kent", badge: "Pure RO Master", category: "Alkaline Water & Purifiers" },
  { name: "Eureka Forbes", badge: "Aquaguard & Vacuum", category: "Active Copper Water" },
  { name: "Oster", badge: "Culinary Precision", category: "Blenders & Food Prep" },
  { name: "Kenwood", badge: "Chef Appliances", category: "Kitchen Stand Mixers" },
  { name: "Dyson", badge: "Air Multiplier & HEPA", category: "Pure Air & Cordless Tech" },
];

export const CUSTOMER_REVIEWS = [
  {
    id: "rev-1",
    name: "Dr. K. Raghavan",
    location: "Avinashi Bypass, Tirupur",
    appliance: "Voltas 2.0 Ton Inverter AC",
    rating: 5,
    comment: "Called Vels Home Appliances at 11 AM when our living room AC stopped cooling before guests arrived. Their technician Murugan arrived by 12:15 PM, diagnosed a faulty dual-run capacitor, replaced it with an OG part, and charged just the fixed ₹500 fee plus part MRP. Impeccable transparency!",
    date: "2 days ago",
  },
  {
    id: "rev-2",
    name: "Ananya Sundaram",
    location: "Besant Nagar, Chennai",
    appliance: "Bosch Front Load 8kg Washer",
    rating: 5,
    comment: "My washing machine was throwing error E18 and water flooded the utility area. The Vels engineer performed a complete drain pump descaling and calibrated the drum balance. Machine runs as quietly as day one. Great glassmorphic booking interface too!",
    date: "1 week ago",
  },
  {
    id: "rev-3",
    name: "S. Manikandan",
    location: "Velachery, Chennai",
    appliance: "Samsung Side-by-Side Refrigerator",
    rating: 5,
    comment: "Fixed ₹500 inspection charge is real! No haggling, polite technicians with ID badges and shoe covers. They fixed the inverter defrost sensor in under 45 minutes with a written 6-month guarantee & warranty card. Highly recommended.",
    date: "2 weeks ago",
  },
];
